label variable RECID "Record identification."
label variable WGHT_PER "Person weight."
label variable WGHT_HSD "Household weight."
label variable AGEC "Age of respondent at time of the survey interview."
label variable AGEDC "Age of respondent at time of the survey interview."
label variable AGEGR5 "Age group of the respondent (groups of 5)."
label variable AGEGR10 "Age group of the respondent (groups of 10)."
label variable SEX "Sex of respondent."
label variable MARSTAT "Marital status of the respondent."
label variable SEXPR "Sex of the respondent's spouse/partner within the household."
label variable PRTYPEC "Type of partner the respondent has within the household."
label variable CHRINHSDC "Number of respondent's child(ren) living in the household (a"
label variable CHRTIME6 "Age group of respondent's single child(ren) living in the ho"
label variable PARHSDC "Type of parents the respondent has within the household."
label variable PRTCHD_1C "Type of parents child 1 has within the household."
label variable PRTCHD_2C "Type of parents child 2 has within the household."
label variable PRTCHD_3C "Type of parents child 3 has within the household."
label variable PRTCHD_4C "Type of parents child 4 has within the household."
label variable PRTCHD_5C "Type of parents child 5 has within the household."
label variable PRTCHD_6C "Type of parents child 6 has within the household."
label variable PRTCHD_7C "Type of parents child 7 has within the household."
label variable LIVARR08 "Living arrangement of respondent's household."
label variable LIVARR12 "Living arrangement of respondent's household."
label variable HSDSIZEC "Household size of respondent."
label variable FAMTYPE "Respondent's type of family structure."
label variable MULTIGENC "Three generations or more family in respondent's household."
label variable CHH0014C "Number of children aged from 0 to 14 years living in the res"
label variable PRV "Province of residence of the respondent."
label variable REGION "Region of residence of the respondent."
label variable LUC_RST "Population centres indicator."
label variable GU_Q110 "When you were born or adopted at birth, were you living with"
label variable GU_Q120 "Until you were 15, did you always live with both of your bir"
label variable GU_Q130C "When you were born, did you live with your birth or adoptive"
label variable GU_Q150C "When you were born, did you live with your birth or adoptive"
label variable GU_Q170 "Have your birth/adoptive parents ever lived together in a co"
label variable GU_Q180 "Was that before or after you were born?"
label variable GU_Q190 "When you were born (or adopted at birth), were your parents"
label variable GU_Q210 "Were they ever married (to each other)?"
label variable BRTHMCAN "Country of birth of the respondent's mother."
label variable EDUM5 "Highest level of education obtained by the respondent's moth"
label variable EDUM10 "Highest level of education obtained by the respondent's moth"
label variable BRTHFCAN "Country of birth of the respondent's father."
label variable EDUF5 "Highest level of education obtained by the respondent's fath"
label variable EDUF10 "Highest level of education obtained by the respondent's fath"
label variable LHH_Q110 "Have you always lived with at least one of your parents? By"
label variable AGE_RETHOMLC "Age of respondent when last came back home."
label variable REA_RETHOML_C01 "Main reason for last return to parental household... Job end"
label variable REA_RETHOML_C02 "Main reason for last return to parental household... Relatio"
label variable REA_RETHOML_C03 "Main reason for last return to parental household... Financi"
label variable REA_RETHOML_C04 "Main reason for last return to parental household... Obtaine"
label variable REA_RETHOML_C05 "Main reason for last return to parental household... End of"
label variable REA_RETHOML_C06 "Main reason for last return to parental household... Other."
label variable LHN_Q110 "Have you left your parent's home more than once to live on y"
label variable NO_LFTHOMC "Number of times the respondent left home to live on his own."
label variable AGE_LFTHOMFC "Age of respondent when first left home to live on his own."
label variable REA_LFTHOMF_C01 "Main reason for first move from parental household... To att"
label variable REA_LFTHOMF_C02 "Main reason for first move from parental household... To mov"
label variable REA_LFTHOMF_C03 "Main reason for first move from parental household... To get"
label variable REA_LFTHOMF_C04 "Main reason for first move from parental household... To be"
label variable REA_LFTHOMF_C05 "Main reason for first move from parental household... Immigr"
label variable REA_LFTHOMF_C06 "Main reason for first move from parental household... Family"
label variable REA_LFTHOMF_C07 "Main reason for first move from parental household... To tra"
label variable REA_LFTHOMF_C08 "Main reason for first move from parental household... Other"
label variable AGE_RETHOMFC "Age of respondent when first came back home."
label variable REA_RETHOMF_C01 "Main reason for first return to parental household... Job en"
label variable REA_RETHOMF_C02 "Main reason for first return to parental household... Relati"
label variable REA_RETHOMF_C03 "Main reason for first return to parental household... Financ"
label variable REA_RETHOMF_C04 "Main reason for first return to parental household... Obtain"
label variable REA_RETHOMF_C05 "Main reason for first return to parental household... End of"
label variable REA_RETHOMF_C06 "Main reason for first return to parental household... Other"
label variable AGE_LFTHOMLC "Age of respondent when last left home to live on his own."
label variable REA_LFTHOML_C01 "Main reason for last move from parental household... To atte"
label variable REA_LFTHOML_C02 "Main reason for last move from parental household... To move"
label variable REA_LFTHOML_C03 "Main reason for last move from parental household... To get"
label variable REA_LFTHOML_C04 "Main reason for last move from parental household... To be i"
label variable REA_LFTHOML_C05 "Main reason for last move from parental household... Immigra"
label variable REA_LFTHOML_C06 "Main reason for last move from parental household... Family"
label variable REA_LFTHOML_C07 "Main reason for last move from parental household... To trav"
label variable REA_LFTHOML_C08 "Main reason for last move from parental household... Other r"
label variable TOT_UNION_C "Total number of unions (marriage and common-law)."
label variable NO_MARREVERC "Number of marriages the respondent has ever had."
label variable NO_MARR_NOCLC "Number of marriages not preceded by common-law union."
label variable NO_CL_FOMARRC "Number of common-law unions followed by a marriage."
label variable LEG_MARSTAT "Current legal marital status of the respondent."
label variable EVER_CL "Respondent ever been in a common-law relationship."
label variable EVER_LEGMARR "Respondent ever legally married."
label variable MA0_RANKC "Rank of current marriage of respondent between all the possi"
label variable AGE_MA0C "Age of respondent at start of current marriage."
label variable MA0_Q108 "Have you ever lived with a common-law partner, even if it wa"
label variable MA0_Q120 "What was your spouse's marital status before entering into t"
label variable AGEDIFGR_MA0 "Age difference between respondent and spouse - current marri"
label variable AGE_SEP_MA0C "Age of respondent at time of separation from current marriag"
label variable NO_CHSPOC "Number of spouse's children the respondent did not raise."
label variable NO_CHU19SPOC "Number of spouse's children 18 years of age or younger the r"
label variable MA0_Q150 "Did you and your spouse live common-law relationship before"
label variable AGE_CL_MA0C "Age of respondent at start of common-law before current marr"
label variable MA0_Q220 "Is this your first marriage?"
label variable MA1_RANKC "Rank of first marriage of respondent between all the possibl"
label variable AGE_MA1C "Age of respondent at start of first marriage."
label variable AGEDIFGR_MA1 "Age difference between respondent and spouse - first marriag"
label variable MA1_Q150 "Did you and your first spouse live in common-law relationshi"
label variable AGE_CL_MA1C "Age of respondent at start of common-law before first marria"
label variable MA1_Q165 "Were any children born from your first marriage?"
label variable MA1_Q170 "Did your first marriage end in:"
label variable AGE_SEP_MA1C "Age of respondent at time of separation from first marriage."
label variable AGE_DIV_MA1C "Age of respondent at time of divorce from first marriage."
label variable MA1_Q220 "Is your current marriage your second?"
label variable MA1_Q230 "Have you been legally married a second time?"
label variable MA2_RANKC "Rank of second marriage of respondent between all the possib"
label variable AGE_MA2C "Age of respondent at start of second marriage."
label variable AGEDIFGR_MA2 "Age difference between respondent and spouse - second marria"
label variable MA2_Q150 "Did you and your second spouse live in common-law relationsh"
label variable AGE_CL_MA2C "Age of respondent at start of common-law before second marri"
label variable MA2_Q165 "Were any children born from your second marriage?"
label variable MA2_Q170 "Did your second marriage end in:"
label variable AGE_SEP_MA2C "Age of respondent at time of separation from second marriage"
label variable AGE_DIV_MA2C "Age of respondent at time of divorce from second marriage."
label variable MA2_Q220 "Is your current marriage your third?"
label variable MA2_Q230 "Have you been legally married a third time?"
label variable MA3_RANKC "Rank of third marriage of respondent between all the possibl"
label variable AGE_MA3C "Age of respondent at start of third marriage."
label variable MA3_Q150 "Did you and your third spouse live in a common-law relations"
label variable AGE_CL_MA3C "Age of respondent at start of common-law before third marria"
label variable MA3_Q165 "Were any children born from your third marriage?"
label variable MA3_Q170C "Did your third marriage end in:"
label variable AGE_SEP_MA3C "Age of respondent at time of separation from third marriage."
label variable AGE_DIV_MA3C "Age of respondent at time of divorce from third marriage."
label variable PR_CL "Respondent is currently living with a common-law partner."
label variable CU0_Q107 "Have you ever been a partner in a common-law relationship th"
label variable CU0_RANKC "Rank of current common-law union of respondent between all t"
label variable AGE_CU0C "Age of respondent at start of current common-law."
label variable CU0_Q120 "What was your partner's marital status before entering into"
label variable AGEDIFGR_CU0 "Age difference between respondent and partner - current comm"
label variable CU0_Q140 "Did your partner live common-law with anyone else before ent"
label variable NO_CHCLPRC "Number of children of common-law partner that the respondent"
label variable NO_CHU19CLPRC "Number of children younger than 19 years of age, of common-l"
label variable CU0_Q220 "Have you had a previous common-law relationship that was not"
label variable CU1_RANKC "Rank of first common-law union of respondent between all the"
label variable AGE_CU1C "Age of respondent at start of first common-law."
label variable AGEDIFGR_CU1 "Age difference between respondent and partner - first common"
label variable CU1_Q170 "Did this union end by separation or by the death of your par"
label variable AGE_SEP_CU1C "Age of respondent at time of separation from first common-la"
label variable CU1_Q190 "Were any children born from this union?"
label variable CU1_Q230 "Have you been a partner in any other common-law relationship"
label variable CU2_RANKC "Rank of second common-law union of respondent between all th"
label variable AGE_CU2C "Age of respondent at start of second common-law."
label variable AGEDIFGR_CU2 "Age difference between respondent and partner - second commo"
label variable CU2_Q170 "Did this union end by separation or by the death of your par"
label variable AGE_SEP_CU2C "Age of respondent at time of separation from second common-l"
label variable CU2_Q190 "Were any children born from this union?"
label variable CU2_Q230 "Have you been a partner in any other common-law relationship"
label variable CU3_RANKC "Rank of third common-law union of respondent between all the"
label variable AGE_CU3C "Age of respondent at start of third common-law."
label variable CU3_Q170 "Did this union end by separation or by the death of your par"
label variable AGE_SEP_CU3C "Age of respondent at time of separation from third common-la"
label variable CU3_Q190 "Were any children born from this union?"
label variable NO_CL_NOMARRC "Number of common-law relationships the respondent has ever h"
label variable NO_SEPDIV_LIFE "Number of separation/divorce that the respondent has had in"
label variable MAC_Q110 "What is the main reason why you married your current spouse"
label variable WEVER_MARR "Respondent expects to marry or re-marry."
label variable MAI_Q145 "When do you plan to get (re)married?"
label variable MCI_Q150 "What is the most important reason why you intend to marry yo"
label variable CLI_Q160 "What is the main reason why you intend to continue living in"
label variable LAT_Q120 "Are you currently in an intimate couple relationship with so"
label variable AGE_LATC "Age of respondent at start of non-cohabiting relationship."
label variable AGEDIFGR_LAT "Age of difference between respondent and partner at start of"
label variable RSH_Q125 "What is the reason why you are living apart? Is it because:"
label variable RSH_Q131 "How far does your spouse/partner live from you? Is it:"
label variable RSH_Q132 "How many of your closest family and friends know about your"
label variable RSH_Q133 "Do you intend to live with your current spouse/partner?"
label variable RSH_Q134 "When do you intend to live with your current spouse/partner?"
label variable CUI_Q150 "Do you think you could ever live in a common-law relationshi"
label variable COR_Q010 "Have you ever raised step-children? By step-children we mean"
label variable COR_Q020 "Have you ever adopted children? (Exclude any step-children m"
label variable COR_Q031 "Have you ever fathered a child?"
label variable COR_Q041 "Have you ever given birth to a child?"
label variable COR_Q070 "Do you have any grandchildren?"
label variable NO_GRNDCHDC "Number of grandchildren the respondent has."
label variable TOTALCHDC "Total number of children raised by respondent."
label variable SEXCHD_1 "Sex of Child_1."
label variable SEXCHD_2 "Sex of Child_2."
label variable SEXCHD_3 "Sex of Child_3."
label variable SEXCHD_4 "Sex of Child_4."
label variable SEXCHD_5 "Sex of Child_5."
label variable SEXCHD_6 "Sex of Child_6."
label variable SEXCHD_7 "Sex of Child_7."
label variable AGECHD_1C "Age of Child_1."
label variable AGECHD_2C "Age of child_2."
label variable AGECHD_3C "Age of child_3."
label variable AGECHD_4C "Age of child_4."
label variable AGECHD_5C "Age of child_5."
label variable AGECHD_6C "Age of child_6."
label variable AGECHD_7C "Age of child_7."
label variable CHDDECC "Number of respondent's children deceased."
label variable AGE_CHDBORN_1C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDBORN_2C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDBORN_3C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDBORN_4C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDBORN_5C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDBORN_6C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDBORN_7C "Age of respondent at birth of Child_1, if biological child."
label variable AGE_CHDJOIN_HOM_1C "Age of respondent when Child_1 joined home."
label variable AGE_CHDJOIN_HOM_2C "Age of respondent when Child_1 joined home."
label variable AGE_CHDJOIN_HOM_3C "Age of respondent when Child_1 joined home."
label variable AGE_CHDJOIN_HOM_4C "Age of respondent when Child_1 joined home."
label variable AGE_CHDJOIN_HOM_5C "Age of respondent when Child_1 joined home."
label variable AGE_CHDJOIN_HOM_6C "Age of respondent when Child_1 joined home."
label variable AGE_CHDJOIN_HOM_7C "Age of respondent when Child_1 joined home."
label variable HHLDCHD_1 "Respondent's Child_1 is a member of the household."
label variable HHLDCHD_2 "Child_2 is a member of the household."
label variable HHLDCHD_3 "Child_3 is a member of the household."
label variable HHLDCHD_4 "Child_4 is a member of the household."
label variable HHLDCHD_5 "Child_5 is a member of the household."
label variable HHLDCHD_6C "Child_6 is a member of the household."
label variable HHLDCHD_7C "Child_7 is a member of the household."
label variable CHDINFTC "Number of respondent's children living in household full-tim"
label variable CHDINPTC "Number of respondent's children living in household part-tim"
label variable CHDOUTC "Number of respondent's children living outside household."
label variable HHLDSTAT_1 "Household status of the respondent's Child_1."
label variable HHLDSTAT_2 "Household status of the respondent's child_2."
label variable HHLDSTAT_3 "Household status of the respondent's child_3."
label variable HHLDSTAT_4 "Household status of the respondent's child_4."
label variable HHLDSTAT_5 "Household status of the respondent's child_5."
label variable HHLDSTAT_6C "Household status of the respondent's child_6."
label variable HHLDSTAT_7C "Household status of the respondent's child_7."
label variable RCI_Q130_01 "Is/Was RCI_Q100_01 a birth, step or adopted child?"
label variable RCI_Q130_02 "Is/Was ^RCI_Q100_02 a birth, step- or adopted child?"
label variable RCI_Q130_03 "Is/Was ^RCI_Q100_03 a birth, step- or adopted child?"
label variable RCI_Q130_04C "Is/Was ^RCI_Q100_04 a birth, step- or adopted child?"
label variable RCI_Q130_05 "Is/Was ^RCI_Q100_05 a birth, step- or adopted child?"
label variable RCI_Q130_06C "Is/Was ^RCI_Q100_06 a birth, step- or adopted child?"
label variable RCI_Q130_07 "Is/Was ^RCI_Q100_07 a birth, step- or adopted child?"
label variable RCI_Q165_01 "Why does RCI_Q100_01 live in your household only part of the"
label variable RCI_Q165_02 "Why does ^RCI_Q100_02 live in your household only part of th"
label variable RCI_Q165_03 "Why does ^RCI_Q100_03 live in your household only part of th"
label variable RCI_Q165_04 "Why does ^RCI_Q100_04 live in your household only part of th"
label variable RCI_Q165_05C "Why does ^RCI_Q100_05 live in your household only part of th"
label variable RCI_Q165_06C "Why does ^RCI_Q100_06 live in your household only part of th"
label variable RCI_Q165_07C "Why does ^RCI_Q100_07 live in your household only part of th"
label variable RCI_Q170_01C "Who does RCI_Q100_01 live with the rest of the time?"
label variable RCI_Q170_02 "Who does ^RCI_Q100_02 live with the rest of the time?"
label variable RCI_Q170_03 "Who does ^RCI_Q100_03 live with the rest of the time?"
label variable RCI_Q170_04C "Who does ^RCI_Q100_04 live with the rest of the time?"
label variable RCI_Q170_05C "Who does ^RCI_Q100_05 live with the rest of the time?"
label variable RCI_Q170_06C "Who does ^RCI_Q100_06 live with the rest of the time?"
label variable RCI_Q170_07C "Who does ^RCI_Q100_07 live with the rest of the time?"
label variable CCP_Q100_01 "In the past 12 months, have you used any form of child care"
label variable CCP_Q100_02 "In the past 12 months, have you used any form of child care"
label variable CCP_Q100_03 "In the past 12 months, have you used any form of child care"
label variable CCP_Q100_04 "In the past 12 months, have you used any form of child care"
label variable CCP_Q105_01 "Did you use this child care arrangement on a regular basis?"
label variable CCP_Q105_02 "Did you use this child care arrangement on a regular basis?"
label variable CCP_Q105_03 "Did you use this child care arrangement on a regular basis?"
label variable CCP_Q105_04 "Did you use this child care arrangement on a regular basis?"
label variable CCP_Q110_01C "Which type of child care arrangement best describes the one"
label variable CCP_Q110_02C "Which type of child care arrangement best describes the one"
label variable CCP_Q110_03 "Which type of child care arrangement best describes the one"
label variable CCP_Q110_04 "Which type of child care arrangement best describes the one"
label variable CCP_Q115_01 "More specifically, was this arrangement:"
label variable CCP_Q115_02 "More specifically, was this arrangement:"
label variable CCP_Q115_03C "More specifically, was this arrangement:"
label variable CCP_Q115_04C "More specifically, was this arrangement:"
label variable CCP_Q120_01 "Where was this child care located? Was it:"
label variable CCP_Q120_02 "Where was this child care located?"
label variable CCP_Q120_03 "Where was this child care located?"
label variable CCP_Q120_04 "Where was this child care located?"
label variable CCP_Q125_01 "What is the relationship between you and the person(s) who m"
label variable CCP_Q125_02C "What is the relationship between you and the person(s) who m"
label variable CCP_Q125_03C "What is the relationship between you and the person(s) who m"
label variable CCP_Q125_04C "What is the relationship between you and the person(s) who m"
label variable CCS_Q100_01 "In the past 12 months, have you used any form of child care"
label variable CCS_Q100_02 "In the past 12 months, have you used any form of child care"
label variable CCS_Q100_03 "In the past 12 months, have you used any form of child care"
label variable CCS_Q100_04 "In the past 12 months, have you used any form of child care"
label variable CCS_Q105_01 "Did you use this child care arrangement on a regular basis?"
label variable CCS_Q105_02 "Did you use this child care arrangement on a regular basis?"
label variable CCS_Q105_03 "Did you use this child care arrangement on a regular basis?"
label variable CCS_Q105_04 "Did you use this child care arrangement on a regular basis?"
label variable CCS_Q110_01C "Which type of child care arrangement best describes the one"
label variable CCS_Q110_02 "Which type of child care arrangement best describes the one"
label variable CCS_Q110_03 "Which type of child care arrangement best describes the one"
label variable CCS_Q110_04 "Which type of child care arrangement best describes the one"
label variable CCS_Q120_01 "Where was this child care located? Was it :"
label variable CCS_Q120_02 "Where was this child care located?"
label variable CCS_Q120_03 "Where was this child care located?"
label variable CCS_Q120_04 "Where was this child care located?"
label variable CCS_Q125_01 "What is the relationship between you and the person(s) who m"
label variable CCS_Q125_02 "What is the relationship between you and the person(s) who m"
label variable CCS_Q125_03 "What is the relationship between you and the person(s) who m"
label variable CCS_Q125_04C "What is the relationship between you and the person(s) who m"
label variable CCA_Q620_01C "What is the main reason why you chose this type of child car"
label variable CCA_Q620_02 "What is the main reason why you chose this type of child car"
label variable CCA_Q620_03 "What is the main reason why you chose this type of child car"
label variable CCA_Q620_04C "What is the main reason why you chose this type of child car"
label variable CCA_Q650_01C "In the past month, how often have you used this child care a"
label variable CCA_Q650_02 "In the past month, how often have you used this child care a"
label variable CCA_Q650_03C "In the past month, how often have you used this child care a"
label variable CCA_Q650_04C "In the past month, how often have you used this child care a"
label variable CCA_Q655_01 "For about how many hours per week?"
label variable CCA_Q655_02 "For about how many hours per week?"
label variable CCA_Q655_03 "For about how many hours per week?"
label variable CCA_Q655_04 "For about how many hours per week?"
label variable CCA_Q660_01 "How old was Child_1 when you first started using this child"
label variable CCA_Q660_02 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q660_03 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q660_04 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q661_01 "How old was Child_1 when you first started using this child"
label variable CCA_Q661_02 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q661_03 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q661_04 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q662_01 "How old was Child_1 when you first started using this child"
label variable CCA_Q662_02 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q662_03 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q662_04 "How old was ^RCI_Q100 when you first started using this chil"
label variable CCA_Q675_01 "How satisfied are you with the overall quality of the (main)"
label variable CCA_Q675_02 "How satisfied are you with the overall quality of the (main)"
label variable CCA_Q675_03 "How satisfied are you with the overall quality of the (main)"
label variable CCA_Q675_04 "How satisfied are you with the overall quality of the (main)"
label variable CCA_Q710_01 "Do you use other types of child care arrangements other than"
label variable CCA_Q710_02 "Do you use other types of child care arrangements other than"
label variable CCA_Q710_03 "Do you use other types of child care arrangements other than"
label variable CCA_Q710_04 "Do you use other types of child care arrangements other than"
label variable CHDCARE_DAY_COST_1 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_DAY_COST_2 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_DAY_COST_3 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_DAY_COST_4 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_WK_COST_1 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_WK_COST_2 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_WK_COST_3 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_WK_COST_4 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_MTH_COST_1 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_MTH_COST_2 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_MTH_COST_3 "On average, the total amount of money spent on child care ar"
label variable CHDCARE_MTH_COST_4 "On average, the total amount of money spent on child care ar"
label variable AGE_HHC_LHOM_1C "Age of respondent when household Child_1 last left home."
label variable AGE_HHC_LHOM_2C "Age of respondent when household Child_1 last left home."
label variable AGE_HHC_LHOM_3C "Age of respondent when household Child_1 last left home."
label variable AGE_HHC_LHOM_4C "Age of respondent when household Child_1 last left home."
label variable AGE_HHC_LHOM_5C "Age of respondent when household Child_1 last left home."
label variable AGE_HHC_LHOM_6C "Age of respondent when household Child_1 last left home."
label variable AGE_HHC_LHOM_7C "Age of respondent when household Child_1 last left home."
label variable AGE_NHHC_LHOM_1C "Age of respondent when non-household Child_1 last left home."
label variable AGE_NHHC_LHOM_2C "Age of respondent when non-household Child_1 last left home."
label variable AGE_NHHC_LHOM_3C "Age of respondent when non-household Child_1 last left home."
label variable AGE_NHHC_LHOM_4C "Age of respondent when non-household Child_1 last left home."
label variable AGE_NHHC_LHOM_5C "Age of respondent when non-household Child_1 last left home."
label variable AGE_NHHC_LHOM_6C "Age of respondent when non-household Child_1 last left home."
label variable AGE_NHHC_LHOM_7C "Age of respondent when non-household Child_1 last left home."
label variable AGE_DCGE15_LHOM_1 "Age of respondent when deceased Child_1, (aged of 15 and mor"
label variable AGE_DCGE15_LHOM_2 "Age of respondent when deceased child_2, aged of 15 or more,"
label variable AGE_DCGE15_LHOM_3 "Age of respondent when deceased child_3, aged of 15 or more,"
label variable AGE_DCGE15_LHOM_4 "Age of respondent when deceased child_4, aged of 15 or more,"
label variable AGE_DCGE15_LHOM_5 "Age of respondent when deceased child_5, aged of 15 or more,"
label variable AGE_DCGE15_LHOM_6 "Age of respondent when deceased child_6, aged of 15 or more,"
label variable AGE_DCGE15_LHOM_7 "Age of respondent when deceased child_7, aged of 15 or more,"
label variable REA_NHH_LHOM_C01_1 "Reason non-household Child_1 last left household: To get ma"
label variable REA_NHH_LHOM_C01_2 "Reason non-household child_2 last left household - to get ma"
label variable REA_NHH_LHOM_C01_3 "Reason non-household child_3 last left household - to get ma"
label variable REA_NHH_LHOM_C01_4 "Reason non-household child_4 last left household - to get ma"
label variable REA_HH_LHOM_C01_1 "Reason Child_1 last left household: To get married, live wit"
label variable REA_HH_LHOM_C01_2 "Reason child_2 last left household - to get married."
label variable REA_HH_LHOM_C01_3 "Reason child_3 last left household - to get married."
label variable REA_HH_LHOM_C01_4 "Reason child_4 last left household - to get married."
label variable REA_DC_LHOM_C01_1 "Reason (deceased) Child_1 last left household: To get marrie"
label variable REA_DC_LHOM_C01_2 "Reason (deceased) child_2 last left household - to get marri"
label variable REA_DC_LHOM_C01_3 "Reason (deceased) child_3 last left household - to get marri"
label variable REA_DC_LHOM_C01_4 "Reason (deceased) child_4 last left household - to get marri"
label variable REA_NHH_LHOM_C02_1 "Reason non-household Child_1 last left household: job relate"
label variable REA_NHH_LHOM_C02_2 "Reason non-household child_2 last left household - job relat"
label variable REA_NHH_LHOM_C02_3 "Reason non-household child_3 last left household - job relat"
label variable REA_NHH_LHOM_C02_4 "Reason non-household child_4 last left household - job relat"
label variable REA_HH_LHOM_C02_1 "Reason Child_1 last left household: job related reasons."
label variable REA_HH_LHOM_C02_2 "Reason child_2 last left household - job related reasons."
label variable REA_HH_LHOM_C02_3 "Reason child_3 last left household - job related reasons."
label variable REA_HH_LHOM_C02_4 "Reason child_4 last left household - job related reasons."
label variable REA_DC_LHOM_C02_1 "Reason (deceased) Child_1 last left household: job related r"
label variable REA_DC_LHOM_C02_2 "Reason (deceased) child_2 last left household - job related"
label variable REA_DC_LHOM_C02_3 "Reason (deceased) child_3 last left household - job related"
label variable REA_DC_LHOM_C02_4 "Reason (deceased) child_4 last left household - job related"
label variable REA_NHH_LHOM_C03_1 "Reason non-household Child_1 last left household: to live al"
label variable REA_NHH_LHOM_C03_2 "Reason non-household child_2 last left household - to live a"
label variable REA_NHH_LHOM_C03_3 "Reason non-household child_3 last left household - to live a"
label variable REA_NHH_LHOM_C03_4 "Reason non-household child_4 last left household - to live a"
label variable REA_HH_LHOM_C03_1 "Reason Child_1 last left household: to live alone."
label variable REA_HH_LHOM_C03_2 "Reason child_2 last left household - to live alone."
label variable REA_HH_LHOM_C03_3 "Reason child_3 last left household - to live alone."
label variable REA_HH_LHOM_C03_4 "Reason child_4 last left household - to live alone."
label variable REA_DC_LHOM_C03_1 "Reason (deceased) Child_1 last left household: to live alone"
label variable REA_DC_LHOM_C03_2 "Reason (deceased) child_2 last left household - to live alon"
label variable REA_DC_LHOM_C03_3 "Reason (deceased) child_3 last left household - to live alon"
label variable REA_DC_LHOM_C03_4 "Reason (deceased) child_4 last left household - to live alon"
label variable REA_NHH_LHOM_C04_1 "Reason non-household Child_1 last left household: to live wi"
label variable REA_NHH_LHOM_C04_2 "Reason non-household child_2 last left household - to live w"
label variable REA_NHH_LHOM_C04_3 "Reason non-household child_3 last left household - to live w"
label variable REA_NHH_LHOM_C04_4 "Reason non-household child_4 last left household - to live w"
label variable REA_HH_LHOM_C04_1 "Reason Child_1 last left household: to live with other paren"
label variable REA_HH_LHOM_C04_2 "Reason child_2 last left household - to live with other pare"
label variable REA_HH_LHOM_C04_3 "Reason child_3 last left household - to live with other pare"
label variable REA_HH_LHOM_C04_4 "Reason child_4 last left household - to live with other pare"
label variable REA_DC_LHOM_C04_1C "Reason (deceased) Child_1 last left household: to live with"
label variable REA_DC_LHOM_C04_2 "Reason (deceased) child_2 last left household - to live with"
label variable REA_DC_LHOM_C04_3 "Reason (deceased) child_3 last left household - to live with"
label variable REA_DC_LHOM_C04_4 "Reason (deceased) child_4 last left household - to live with"
label variable REA_NHH_LHOM_C05_1 "Reason non-household Child_1 last left household: to live wi"
label variable REA_NHH_LHOM_C05_2 "Reason non-household child_2 last left household - to live w"
label variable REA_NHH_LHOM_C05_3 "Reason non-household child_3 last left household - to live w"
label variable REA_NHH_LHOM_C05_4 "Reason non-household child_4 last left household - to live w"
label variable REA_HH_LHOM_C05_1 "Reason Child_1 last left household: to live with relatives ("
label variable REA_HH_LHOM_C05_2 "Reason child_2 last left household - to live with relatives"
label variable REA_HH_LHOM_C05_3 "Reason child_3 last left household - to live with relatives"
label variable REA_HH_LHOM_C05_4 "Reason child_4 last left household - to live with relatives"
label variable REA_DC_LHOM_C05_1 "Reason (deceased) Child_1 last left household: to live with"
label variable REA_DC_LHOM_C05_2 "Reason (deceased) child_2 last left household - to live with"
label variable REA_DC_LHOM_C05_3 "Reason (deceased) child_3 last left household - to live with"
label variable REA_DC_LHOM_C05_4 "Reason (deceased) child_4 last left household - to live with"
label variable REA_NHH_LHOM_C06_1 "Reason non-household Child_1 last left household: child plac"
label variable REA_NHH_LHOM_C06_2 "Reason non-household child_2 last left household - child pla"
label variable REA_NHH_LHOM_C06_3 "Reason non-household child_3 last left household - child pla"
label variable REA_NHH_LHOM_C06_4 "Reason non-household child_4 last left household - child pla"
label variable REA_HH_LHOM_C06_1C "Reason Child_1 last left household: child placed in institut"
label variable REA_HH_LHOM_C06_2 "Reason child_2 last left household - child placed in institu"
label variable REA_HH_LHOM_C06_3 "Reason child_3 last left household - child placed in institu"
label variable REA_HH_LHOM_C06_4 "Reason child_4 last left household - child placed in institu"
label variable REA_DC_LHOM_C06_1 "Reason (deceased) Child_1 last left household: child placed"
label variable REA_DC_LHOM_C06_2 "Reason (deceased) child_2 last left household - child placed"
label variable REA_DC_LHOM_C06_3 "Reason (deceased) child_3 last left household - child placed"
label variable REA_DC_LHOM_C06_4 "Reason (deceased) child_4 last left household - child placed"
label variable REA_NHH_LHOM_C07_1 "Reason non-household Child_1 dernière left household: school"
label variable REA_NHH_LHOM_C07_2 "Reason non-household child_2 last left household - school re"
label variable REA_NHH_LHOM_C07_3 "Reason non-household child_3 last left household - school re"
label variable REA_NHH_LHOM_C07_4 "Reason non-household child_4 last left household - school re"
label variable REA_HH_LHOM_C07_1 "Reason Child_1 last left household: school related reasons."
label variable REA_HH_LHOM_C07_2 "Reason child_2 last left household - school related reasons."
label variable REA_HH_LHOM_C07_3 "Reason child_3 last left household - school related reasons."
label variable REA_HH_LHOM_C07_4 "Reason child_4 last left household - school related reasons."
label variable REA_DC_LHOM_C07_1 "Reason (deceased) Child_1 last left household : school relat"
label variable REA_DC_LHOM_C07_2 "Reason (deceased) child_2 last left household - school relat"
label variable REA_DC_LHOM_C07_3 "Reason (deceased) child_3 last left household - school relat"
label variable REA_DC_LHOM_C07_4 "Reason (deceased) child_4 last left household - school relat"
label variable REA_NHH_LHOM_C08_1 "Reason non-household Child_1 last left household: was asked"
label variable REA_NHH_LHOM_C08_2 "Reason non-household child_2 last left household - was asked"
label variable REA_NHH_LHOM_C08_3 "Reason non-household child_3 last left household - was asked"
label variable REA_NHH_LHOM_C08_4 "Reason non-household child_4 last left household - was asked"
label variable REA_HH_LHOM_C08_1 "Reason Child_1 last left household: was asked to leave."
label variable REA_HH_LHOM_C08_2 "Reason child_2 last left household - was asked to leave."
label variable REA_HH_LHOM_C08_3 "Reason child_3 last left household - was asked to leave."
label variable REA_HH_LHOM_C08_4 "Reason child_4 last left household - was asked to leave."
label variable REA_DC_LHOM_C08_1C "Reason (deceased) Child_1 last left household: was asked to"
label variable REA_DC_LHOM_C08_2 "Reason (deceased) child_2 last left household - was asked to"
label variable REA_DC_LHOM_C08_3 "Reason (deceased) child_3 last left household - was asked to"
label variable REA_DC_LHOM_C08_4 "Reason (deceased) child_4 last left household - was asked to"
label variable REA_NHH_LHOM_C09_1 "Reason non-household Child_1 last left household: other."
label variable REA_NHH_LHOM_C09_2 "Reason non-household child_2 last left household - other."
label variable REA_NHH_LHOM_C09_3 "Reason non-household child_3 last left household - other."
label variable REA_NHH_LHOM_C09_4 "Reason non-household child_4 last left household - other."
label variable REA_HH_LHOM_C09_1C "Reason Child_1 last left household: other."
label variable REA_HH_LHOM_C09_2 "Reason child_2 last left household - other."
label variable REA_HH_LHOM_C09_3 "Reason child_3 last left household - other."
label variable REA_HH_LHOM_C09_4 "Reason child_4 last left household - other."
label variable REA_DC_LHOM_C09_1C "Reason (deceased) Child_1 last left household: other."
label variable REA_DC_LHOM_C09_2 "Reason (deceased) child_2 last left household - other."
label variable REA_DC_LHOM_C09_3 "Reason (deceased) child_3 last left household - other."
label variable REA_DC_LHOM_C09_4 "Reason (deceased) child_4 last left household - other."
label variable COM_Q105 "Who in your couple mainly takes care of: ... preparing daily"
label variable COM_Q110 "Who in your couple mainly takes care of:"
label variable COM_Q115 "Who in your couple mainly takes care of: ...doing the dishes"
label variable COM_Q120 "Who in your couple mainly takes care of: ...doing the laundr"
label variable COM_Q125 "Who in your couple mainly takes care of: ...doing the grocer"
label variable COM_Q130 "Who in your couple mainly takes care of: ...doing the garden"
label variable COM_Q135 "Who in your couple mainly takes care of: ...doing outside wo"
label variable COM_Q140 "Who in your couple mainly takes care of: ...organizing the h"
label variable COM_Q145 "Who in your couple mainly takes care of: ...the household fi"
label variable COM_Q150 "Who in your couple mainly makes decisions regarding: ...dail"
label variable COM_Q155 "Who in your couple mainly makes decisions regarding: ...occa"
label variable COM_Q200 "Do you have bank accounts in your sole name only, held in jo"
label variable COM_Q205_C01 "Including income from all sources, such as salary, social as"
label variable COM_Q205_C02 "Including income from all sources, such as salary, social as"
label variable COM_Q205_C03 "Including income from all sources, such as salary, social as"
label variable COM_Q205_C04 "Including income from all sources, such as salary, social as"
label variable COM_Q205_C05 "Including income from all sources, such as salary, social as"
label variable COM_Q210_C01 "(Including income from all sources, such as salary, social a"
label variable COM_Q210_C02 "(Including income from all sources, such as salary, social a"
label variable COM_Q210_C03 "(Including income from all sources, such as salary, social a"
label variable COM_Q210_C04 "(Including income from all sources, such as salary, social a"
label variable COM_Q210_C05 "(Including income from all sources, such as salary, social a"
label variable COM_Q212 "Overall, how would you describe the way you and your spouse/"
label variable COM_Q215 "What is your financial contribution for paying: ... the rent"
label variable COM_Q220 "What is your financial contribution for paying: ... for groc"
label variable COM_Q225 "What is your financial contribution for paying: ... for chil"
label variable COM_Q230 "What is your financial contribution for paying: ... for elec"
label variable COM_Q235 "Usually, after essential expenses are paid, is there any mon"
label variable FR_Q100 "At any time during the past 12 months, have you/has your hou"
label variable FR_Q110 "At any time during the past 12 months, have you/has your hou"
label variable FR_Q120 "At any time during the past 12 months, have you/has your hou"
label variable FR_Q130_C01 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C02 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C03 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C04 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C05 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C06 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C07 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C08 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q130_C09 "How did you get around this/these difficulty(difficulties)?"
label variable FR_Q140 "Thinking of your household's income, (include income from sa"
label variable PR_PREG "Respondent or respondent's spouse/partner is currently pregn"
label variable FI_Q110 "Do you intend to have a/another child sometime?"
label variable NO_CHRIC "Total number of children respondent intends to have includin"
label variable FI_Q125 "When do you expect to have a/another child? Is it:"
label variable FI_Q130 "Have you had an operation or medical procedure that makes it"
label variable FI_Q131 "Did you have that operation or medical procedure for contrac"
label variable FI_Q140 "Some people are not able to have children. Have you ever bee"
label variable FI_Q230 "Has your spouse/partner had an operation or medical procedur"
label variable FI_Q231 "Did your spouse/partner have that operation or medical proce"
label variable FI_Q240 "Has your spouse/partner ever been told that he/she cannot ha"
label variable FI_Q305 "Are you or your spouse/partner currently using any contracep"
label variable FI_Q310_C01 "Please name all of the methods you use or do. Condom."
label variable FI_Q310_C02 "Please name all of the methods you use or do. Birth control"
label variable FI_Q310_C03 "Please name all of the methods you use or do. IUD - Intra-ut"
label variable FI_Q310_C04 "Please name all of the methods you use or do. Diaphragm/Cerv"
label variable FI_Q310_C05 "Please name all of the methods you use or do. Foam/Cream/Jel"
label variable FI_Q310_C06 "Please name all of the methods you use or do. Injectables (e"
label variable FI_Q310_C07C "Please name all of the methods you use or do. Implants (e.g."
label variable FI_Q310_C08 "Please name all of the methods you use or do. Menstrual cycl"
label variable FI_Q310_C09 "Please name all of the methods you use or do. Withdrawal/Pul"
label variable FI_Q310_C10 "Please name all of the methods you use or do. Periodic absti"
label variable FI_Q310_C11C "Please name all of the methods you use or do. Other method."
label variable NIC_Q100_C01 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C02 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C03 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C04 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C05 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C06 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C07 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C08 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C09 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C10 "You mentioned earlier that you do not intend to have a/anoth"
label variable NIC_Q100_C11 "You mentioned earlier that you do not intend to have a/anoth"
label variable FIC_Q100 "In your current relationship, have you and your spouse/partn"
label variable FIC_Q110 "In your current relationship, have you and your spouse/partn"
label variable FIC_Q120 "Have you or your spouse/partner ever seen a doctor or other"
label variable F_CRT_D210 "Respondents who had/adopted a child in last 5 years."
label variable MPL_Q105_C01 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C02 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C03 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C04 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C05 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C06 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C07 "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C08C "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q105_C09C "At the beginning of your pregnancy /At the beginning of your"
label variable MPL_Q107 "Were you studying full-time or part-time?"
label variable MPL_Q108 "Did you have a job or were you self-employed at any time bef"
label variable RTO_Q100 "Were you mainly:"
label variable RTO_Q101 "Was it a full-time or part-time job?"
label variable RTO_Q110 "Before or after the birth/adoption of your (youngest) child,"
label variable RTO_Q120 "What was the main reason you did not take time off after the"
label variable RTO_Q130_C01 "What type of leave was this? Was it: ... Maternity/paternity"
label variable RTO_Q130_C02 "What type of leave was this? Was it: ... Parental leave?"
label variable RTO_Q130_C03 "What type of leave was this? Was it: ... Vacation?"
label variable RTO_Q130_C04 "What type of leave was this? Was it: ... Leave without pay?"
label variable RTO_Q130_C05 "What type of leave was this? Was it: ... Employer program?"
label variable RTO_Q130_C06 "What type of leave was this? Was it: ... Sick leave?"
label variable RTO_Q130_C07 "What type of leave was this? Was it: ... Other."
label variable OTO_Q100 "(Before or after the birth/adoption of your youngest child),"
label variable OTO_Q110_C01 "What type of leave was this? Was it: ... Maternity/paternity"
label variable OTO_Q110_C02 "What type of leave was this? Was it: ... Parental leave?"
label variable OTO_Q110_C03 "What type of leave was this? Was it: ... Vacation?"
label variable OTO_Q110_C04 "What type of leave was this? Was it: ... Leave without pay?"
label variable OTO_Q110_C05 "What type of leave was this? Was it: ... Employer program?"
label variable OTO_Q110_C06 "What type of leave was this? Was it: ... Sick leave?"
label variable OTO_Q110_C07 "What type of leave was this? Was it: ... Other."
label variable RRB_Q100 "Did you receive maternity/or parental benefits after the bir"
label variable RRB_Q110C "For how many weeks?"
label variable RRB_Q120 "What was the main reason you did not receive maternity/or pa"
label variable ORB_Q100 "Did the other parent collect maternity or parental benefits"
label variable ORB_Q110C "For how many weeks did he/she receive benefits?"
label variable SBR_Q100 "Did your employer provide supplementary maternity/parental b"
label variable SBR_Q110C "For how many weeks?"
label variable AGE_DSW_Q101C "Age of the respondent when he/she stopped working at paid jo"
label variable DSW_Q110 "Did you go back to work after your leave for the birth/adopt"
label variable AGECHD_BACKTOWORK "Age of the respondent's youngest child when respondent went"
label variable RTW_Q130 "When you returned to work: ... was it full-time or part-time"
label variable RTW_Q140 "When you returned to work:... did you modify your work hours"
label variable RTW_Q200 "When you returned to work: ... did you have the choice to mo"
label variable RTW_Q210 "When you returned to work: ... did you have the choice to wo"
label variable RTW_Q220 "When you returned to work: ... did you have the choice to wo"
label variable RTW_Q230 "When you returned to work: ... would you have liked to work"
label variable RTW_Q240C "When you returned to work: ... what was the main reason you"
label variable RTW_Q250C "When you returned to work: ... what was the main reason why"
label variable WSL_Q100 "Did you wish to stay home longer?"
label variable WSL_Q110_C01 "What would have allowed you to stay home longer? Higher bene"
label variable WSL_Q110_C02 "What would have allowed you to stay home longer? Benefits of"
label variable WSL_Q110_C03 "What would have allowed you to stay home longer? If my emplo"
label variable WSL_Q110_C04 "What would have allowed you to stay home longer? If employer"
label variable WSL_Q110_C05 "What would have allowed you to stay home longer? If financia"
label variable WSL_Q110_C06 "What would have allowed you to stay home longer? Other."
label variable F_SEP_DIV_LAST20YRS "Respondents who have been separated or divorced in the last"
label variable LDS_Q100 "When you separated/divorced, did you and your ex-spouse/ex-p"
label variable LDS_Q110 "How many are currently 18 or younger?"
label variable PRC_Q100_C01 "What is the primary residence of your child (children)? Res"
label variable PRC_Q100_C02 "What is the primary residence of your child (children)? Ex-"
label variable PRC_Q100_C03 "What is the primary residence of your child (children)? Abo"
label variable PRC_Q100_C04 "What is the primary residence of your child (children)? Som"
label variable PRC_Q110_C01 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q110_C02 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q110_C03 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q110_C04 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q110_C05 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q110_C06 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q110_C07 "How far away does your ex-spouse/ex-partner live from your c"
label variable PRC_Q115C "Does your ex-spouse/ex-partner reside:"
label variable PRC_Q120 "What kind of arrangement or agreement for primary residence"
label variable PRC_Q130_C01 "How was the written arrangement or agreement concluded? Was"
label variable PRC_Q130_C02 "How was the written arrangement or agreement concluded? Was"
label variable PRC_Q130_C03 "How was the written arrangement or agreement concluded? Was"
label variable PRC_Q130_C04 "How was the written arrangement or agreement concluded? Was"
label variable PRC_Q130_C05 "How was the written arrangement or agreement concluded? Was"
label variable NPR_Q100 "What is the main reason why there is no arrangement for the"
label variable ATS_Q120 "What kind of agreement or arrangement do you have to schedul"
label variable ATS_Q130_C01 "How was the written arrangement or agreement concluded? Was"
label variable ATS_Q130_C02 "How was the written arrangement or agreement concluded? Was"
label variable ATS_Q130_C03 "How was the written arrangement or agreement concluded? Was"
label variable ATS_Q130_C04 "How was the written arrangement or agreement concluded? Was"
label variable ATS_Q130_C05 "How was the written arrangement or agreement concluded? Was"
label variable ATS_Q140 "In the past 12 months, overall, would you say that the arran"
label variable ATS_Q145 "What is the main reason why the arrangement has not been fol"
label variable NTS_Q100C "What is the main reason why there is no arrangement (for the"
label variable DAYS_TSHQ110_L12M "Days spent by child in household (last 12 months)."
label variable TSC_Q410 "How satisfied are you with the amount of time you spend with"
label variable TSC_Q450 "How satisfied are you with the amount of time your ex-spouse"
label variable TSC_Q460C "What is the main reason why you are dissatisfied (with the t"
label variable MDC_Q117 "Who makes major decisions about your child/children's health"
label variable FSE_Q100 "Have you ever provided or received any financial support for"
label variable FSE_Q105 "Are you currently providing or receiving financial support f"
label variable FSE_Q110_C01 "What kind of financial support is it? Periodic payments."
label variable FSE_Q110_C02 "What kind of financial support is it? Contribute to househol"
label variable FSE_Q110_C03 "What kind of financial support is it? RRSP, savings for reti"
label variable FSE_Q110_C04C "What kind of financial support is it? Maintaining health pre"
label variable FSE_Q110_C05C "What kind of financial support is it? Paying tuition."
label variable FSE_Q110_C06 "What kind of financial support is it? Gave a specific asset"
label variable FSE_Q110_C07 "What kind of financial support is it? Other."
label variable CSP_Q100 "Have you ever provided or received any financial support for"
label variable CSP_Q105 "Are you currently providing or receiving financial support f"
label variable CSP_Q110_C01 "What kind of financial support is it? Child support (periodi"
label variable CSP_Q110_C02 "What kind of financial support is it? Contribute to househol"
label variable CSP_Q110_C03 "What kind of financial support is it? RESP, savings child's"
label variable CSP_Q110_C04 "What kind of financial support is it? Child's expenses (i.e."
label variable CSP_Q110_C05 "What kind of financial support is it? Other."
label variable CSP_Q150 "What kind of arrangement or agreement for financial support"
label variable CSP_Q160_C01 "How was the written arrangement or agreement concluded? Was"
label variable CSP_Q160_C02 "How was the written arrangement or agreement concluded? Was"
label variable CSP_Q160_C03 "How was the written arrangement or agreement concluded? Was"
label variable CSP_Q160_C04 "How was the written arrangement or agreement concluded? Was"
label variable CSP_Q160_C05 "How was the written arrangement or agreement concluded? Was"
label variable CSP_Q170 "Is this arrangement for this/these child/children support cu"
label variable FSP_Q130C "How often is this financial support being paid?"
label variable FSP_Q135GRP "What was the total amount paid over the last 12 months (for"
label variable FSP_Q320C "In the past 12 months, have you paid all the child support p"
label variable FSR_Q130 "How often is the child financial support being paid?"
label variable FSR_Q135GRP "What was the total amount received over the last 12 months ("
label variable FSR_Q310C "According to your arrangements, and thinking about your chil"
label variable FSR_Q320C "In the past 12 months, have you received all the child suppo"
label variable ACMYRC "Main activity of the respondent in the last 12 months."
label variable EDUSTAT "Full-time or part-time education status for the respondent."
label variable MAR_Q133 "Did you have a job or were you self-employed at any time las"
label variable MAR_Q134 "In the last four weeks, did you look for a job?"
label variable MAR_Q135 "Did you have a job or were you self-employed at any time dur"
label variable MAR_Q136 "Have you ever worked at a job or business?"
label variable WKWE "Number of weeks during the past 12 months the respondent was"
label variable WET_Q120 "Were you mainly:"
label variable WTI_Q110 "Some people do all or some of their paid work at home. Excl"
label variable WTI_Q130 "What is the main reason you do/did some of your work at home"
label variable NAICS2007_C16C "North American Industrial Classification System of the respo"
label variable NOCS2006_C10C "National Occupational Classification (2006) of the responden"
label variable WLY_Q145 "Are you still working for this employer/at this business?"
label variable WLY_Q150 "Which of the following best describes your terms of employme"
label variable WLY_Q160 "Are/Were you a union member or covered by a union contract o"
label variable WHW_Q110 "Did you have more than one paid job last week?"
label variable WKWEHR_C "Number of hours usually worked at all jobs in a week."
label variable WHW_Q160_C01 "Why do/did you usually work less than 30 hours a week? Own i"
label variable WHW_Q160_C02 "Why do/did you usually work less than 30 hours a week? Child"
label variable WHW_Q160_C03 "Why do/did you usually work less than 30 hours a week? Elder"
label variable WHW_Q160_C04 "Why do/did you usually work less than 30 hours a week? Other"
label variable WHW_Q160_C05 "Why do/did you usually work less than 30 hours a week? Going"
label variable WHW_Q160_C06 "Why do/did you usually work less than 30 hours a week? Could"
label variable WHW_Q160_C07 "Why do/did you usually work less than 30 hours a week? Did n"
label variable WHW_Q160_C08 "Why do/did you usually work less than 30 hours a week? Requi"
label variable WHW_Q160_C09 "Why do/did you usually work less than 30 hours a week? Full-"
label variable WHW_Q160_C10 "Why do/did you usually work less than 30 hours a week? Other"
label variable WHW_Q210 "How many days a week did/do you usually work usually work (i"
label variable WHW_Q230 "Which of the following best describes your usual work schedu"
label variable WFR_Q510 "How satisfied are/were you with the balance between your job"
label variable WFR_Q520_C01 "Why are/were you dissatisfied? Not enough time for family (i"
label variable WFR_Q520_C02 "Why are/were you dissatisfied? Spends too much time on job/m"
label variable WFR_Q520_C03 "Why are/were you dissatisfied? Not enough time for other act"
label variable WFR_Q520_C04 "Why are/were you dissatisfied? Cannot find suitable employme"
label variable WFR_Q520_C05 "Why are/were you dissatisfied? Employment related reason(s)"
label variable WFR_Q520_C06 "Why are/were you dissatisfied? Health reasons (include sleep"
label variable WFR_Q520_C07 "Why are/were you dissatisfied? Family related reason(s) (exc"
label variable WFR_Q520_C08 "Why are/were you dissatisfied? Other."
label variable EDUYR "Number of years of elementary and high school education succ"
label variable EOR_Q110 "Have you graduated from high school?"
label variable EOR_Q150 "Have you had any further schooling beyond elementary or high"
label variable EDU5 "Highest level of education obtained by the respondent - 5 gr"
label variable EDU10C "Highest level of education obtained by the respondent - 10 g"
label variable AGE_COMPL_STUDIES_C "Age of respondent at completion of studies?"
label variable F_EOR_Q210 "Country where respondent attained his /her"
label variable ACMPRYRC "Spouse's/partner's main activity during the past 12 months."
label variable MAP_Q120 "Was he/she studying full-time or part-time?"
label variable MAP_Q130 "Did he/she have a job or was he/she self-employed at any tim"
label variable MAP_Q131 "For how many weeks during the past 12 months was he/she empl"
label variable MAP_Q132 "Was he/she mainly:"
label variable MAP_Q135C "In an average week, how many hours did he/she usually work?"
label variable MAP_Q140C "What is the main reason why your pouse/partner usually works"
label variable MAP_Q145 "Is his/her job permanent?"
label variable MAP_Q150 "Did he/she have more than one paid job last week?"
label variable MAP_Q152 "What is the main reason he/she worked at more than one job l"
label variable MAP_Q155 "Which of the following best describes your spouse's / partne"
label variable MAP_Q190 "During the past 12 months, was he/she ever without a job and"
label variable EDUPR5 "Highest level of education obtained by the respondent's spou"
label variable EDUPR10C "Highest level of education obtained by the respondent's spou"
label variable WHI_Q10 "Have you ever worked at a job or business for a period of si"
label variable AGE_WK1BEGC "Age of respondent at the beginning of first work period."
label variable AGE_WK1ENDC "Age of respondent at the end of first work period."
label variable DUR_WK1C "Length of respondent's first work period (in months)."
label variable WH1_Q120 "Were you working 30 hours or more per week?"
label variable WH1_Q210 "Were you mainly:"
label variable WH1_Q230 "From [WH1_Q110M & WH1_Q110Y] to today/the age of [WH1_Q111]"
label variable WH1_Q240 "From [WH1_Q110M & WH1_Q110Y] to today/the age of [WH1_Q111]"
label variable WH1_Q255 "(You mentioned that you were absent from work for more than"
label variable WH1_Q310 "Were you mainly:"
label variable WH1_Q320 "Why did you work less than 30 hours per week?"
label variable WH1_Q330 "From [WH1_Q110M & WH1_Q110Y] to today/the age of [WH1_Q111]"
label variable WH1_Q340 "From [WH1_Q110M & WH1_Q110Y] to today/the age of [WH1_Q111]"
label variable WH1_Q355 "(You mentioned that you were absent from work for more than"
label variable WH1_Q370_C01 "What were the reasons for that absence from work? Seasonal/c"
label variable WH1_Q370_C02 "What were the reasons for that absence from work? Temporary"
label variable WH1_Q370_C03 "What were the reasons for that absence from work? Lack of wo"
label variable WH1_Q370_C04 "What were the reasons for that absence from work? Quit job."
label variable WH1_Q370_C05 "What were the reasons for that absence from work? Fired/disc"
label variable WH1_Q370_C06 "What were the reasons for that absence from work? Business o"
label variable WH1_Q370_C07 "What were the reasons for that absence from work? Moved or t"
label variable WH1_Q370_C08 "What were the reasons for that absence from work? Changed jo"
label variable WH1_Q370_C09 "What were the reasons for that absence from work? Own illnes"
label variable WH1_Q370_C10 "What were the reasons for that absence from work? Returned t"
label variable WH1_Q370_C11 "What were the reasons for that absence from work? Retired."
label variable WH1_Q370_C12 "What were the reasons for that absence from work? Maternity/"
label variable WH1_Q370_C13 "What were the reasons for that absence from work? Child care"
label variable WH1_Q370_C14 "What were the reasons for that absence from work? Eldercare."
label variable WH1_Q370_C15 "What were the reasons for that absence from work? Personal o"
label variable WH1_Q370_C16 "What were the reasons for that absence from work? Other."
label variable WH1_Q370_C17 "What were the reasons for that absence from work? To travel."
label variable WH1_Q410 "Did you return to seasonal work after that absence from work"
label variable WH1_Q420 "From [WH1_Q110M & WH1_Q110Y or] to today/the age of [ WH1_Q1"
label variable WH1_Q470 "Did you start working after being a seasonal worker ?"
label variable WH2_Q100 "Did you start working after that absence from work?"
label variable AGE_WK2BEGC "Age of respondent at the beginning of second work period."
label variable AGE_WK2ENDC "Age of respondent at the end of second work period."
label variable DUR_WK2C "Length of respondent's second work period (in months)."
label variable WH2_Q115 "Did you return to the same work?"
label variable WH2_Q120 "Were you working 30 hours or more per week?"
label variable WH2_Q210 "Were you mainly:"
label variable WH2_Q230 "From [WH2_Q110M & WH2_Q110Y or WH2_Q200M & WH2_Q200Y] to tod"
label variable WH2_Q240 "From [WH2_Q110M & WH2_Q110Y or WH2_Q200M & WH2_Q200Y] to tod"
label variable WH2_Q255 "(You mentioned that you were absent from work for more than"
label variable WH2_Q310 "Were you mainly:"
label variable WH2_Q320 "Why did you work less than 30 hours per week?"
label variable WH2_Q330 "From [WH2_Q110M & WH2_Q110Y or WH2_Q200M & WH2_Q200Y or WH2"
label variable WH2_Q340 "From [ WH2_Q110M & WH2_Q110Y or WH2_Q200M & WH2_Q200Y or W"
label variable WH2_Q355 "(You mentioned that you were absent from work for more than"
label variable WH2_Q370_C01 "What were the reasons for that absence from work? Seasonal"
label variable WH2_Q370_C02 "What were the reasons for that absence from work? Temporary"
label variable WH2_Q370_C03 "What were the reasons for that absence from work? Lack of wo"
label variable WH2_Q370_C04 "What were the reasons for that absence from work? Quit job."
label variable WH2_Q370_C05 "What were the reasons for that absence from work? Fired/disc"
label variable WH2_Q370_C06 "What were the reasons for that absence from work? Business o"
label variable WH2_Q370_C07 "What were the reasons for that absence from work? Moved or t"
label variable WH2_Q370_C08 "What were the reasons for that absence from work? Changed jo"
label variable WH2_Q370_C09 "What were the reasons for that absence from work? Own illnes"
label variable WH2_Q370_C10 "What were the reasons for that absence from work? Returned t"
label variable WH2_Q370_C11 "What were the reasons for that absence from work? Retired."
label variable WH2_Q370_C12 "What were the reasons for that absence from work? Maternity/"
label variable WH2_Q370_C13 "What were the reasons for that absence from work? Child care"
label variable WH2_Q370_C14 "What were the reasons for that absence from work? Eldercare."
label variable WH2_Q370_C15 "What were the reasons for that absence from work? Personal o"
label variable WH2_Q370_C16 "What were the reasons for that absence from work? Other."
label variable WH2_Q370_C17 "What were the reasons for that absence from work? To travel"
label variable WH2_Q410 "Did you return to seasonal work after that absence from work"
label variable WH2_Q420 "From [WH2_Q110M & WH2_Q110Y or WH2_Q260M & WH2_Q260Y or WH"
label variable WH2_Q470 "Did you start working after being a seasonal worker?"
label variable WH3_Q100 "Did you start working after that absence from work?"
label variable AGE_WK3BEGC "Age of respondent at the beginning of third work period."
label variable AGE_WK3ENDC "Age of respondent at the end of third work period."
label variable DUR_WK3C "Length of respondent's third work period (in months)."
label variable WH3_Q115 "Did you return to the same job?"
label variable WH3_Q120 "Were you working 30 hours or more per week?"
label variable WH3_Q210 "Were you mainly:"
label variable WH3_Q230 "From [WH3_Q110M & WH3_Q110Y or WH3_Q200M & WH3_Q200Y ] to to"
label variable WH3_Q240 "From [WH3_Q110M & WH3_Q110Y or WH3_Q200M & WH3_Q200Y] to tod"
label variable WH3_Q255 "(You mentioned that you were absent from work for more than"
label variable WH3_Q310 "Were you mainly:"
label variable WH3_Q320 "Why did you work less than 30 hours per week?"
label variable WH3_Q330 "From [WH3_Q110M & WH3_Q110Y or WH3_Q200M & WH3_Q200Y or WH"
label variable WH3_Q340 "From [ WH3_Q110M & WH3_Q110Y or WH3_Q200M & WH3_Q200Y or W"
label variable WH3_Q355 "(You mentioned that you were absent from work for more than"
label variable WH3_Q370_C01 "What were the reasons for that absence from work? Seasonal/c"
label variable WH3_Q370_C02 "What were the reasons for that absence from work? Temporary"
label variable WH3_Q370_C03 "What were the reasons for that absence from work? Lack of wo"
label variable WH3_Q370_C04 "What were the reasons for that absence from work? Quit job."
label variable WH3_Q370_C05 "What were the reasons for that absence from work? Fired/disc"
label variable WH3_Q370_C06 "What were the reasons for that absence from work? Business o"
label variable WH3_Q370_C07 "What were the reasons for that absence from work? Moved or t"
label variable WH3_Q370_C08 "What were the reasons for that absence from work? Changed jo"
label variable WH3_Q370_C09 "What were the reasons for that absence from work? Own illnes"
label variable WH3_Q370_C10 "What were the reasons for that absence from work? Returned t"
label variable WH3_Q370_C11 "What were the reasons for that absence from work? Retired."
label variable WH3_Q370_C12 "What were the reasons for that absence from work? Maternity/"
label variable WH3_Q370_C13 "What were the reasons for that absence from work? Child care"
label variable WH3_Q370_C14 "What were the reasons for that absence from work? Eldercare."
label variable WH3_Q370_C15 "What were the reasons for that absence from work? Personal o"
label variable WH3_Q370_C16 "What were the reasons for that absence from work? Other."
label variable WH3_Q370_C17 "What were the reasons for that absence from work? To travel"
label variable WH3_Q410 "Did you return to seasonal work after that absence from work"
label variable WH3_Q420 "From [WH3_Q110M & WH3_Q110Y or WH3_Q260M & WH3_Q260Y or WH"
label variable WH3_Q470 "Did you start working after being a seasonal worker?"
label variable WH4_Q100 "Did you start working after that absence from work?"
label variable AGE_WK4BEGC "Age of respondent at the beginning of fourth work period."
label variable AGE_WK4ENDC "Age of respondent at the end of fourth work period."
label variable DUR_WK4C "Length of respondent's fourth work period (in months)."
label variable WH4_Q115 "Did you return to the same job?"
label variable WH4_Q120 "Were you working 30 hours or more per week?"
label variable WH4_Q210 "Were you mainly:"
label variable WH4_Q230 "From [WH4_Q110M & WH4_Q110Y or WH4_Q200M & WH4_Q200Y] to tod"
label variable WH4_Q240 "From [WH4_Q110M & WH4_Q110Y or WH4_Q200M & WH4_Q200Y] to tod"
label variable WH4_Q255 "(You mentioned that you were absent from work for more than"
label variable WH4_Q310C "Were you mainly:"
label variable WH4_Q320 "Why did you work less than 30 hours per week?"
label variable WH4_Q330 "From [WH4_Q110M & WH4_Q110Y or WH4_Q260M & WH4_Q260Y or WH"
label variable WH4_Q340 "From [ WH4_Q110M & WH4_Q110Y or WH4_Q260M & WH4_Q260Y or W"
label variable WH4_Q355 "(You mentioned that you were absent from work for more than"
label variable WH4_Q370_C01 "What were the reasons for that absence from work? Seasonal/c"
label variable WH4_Q370_C02 "What were the reasons for that absence from work? Temporary"
label variable WH4_Q370_C03 "What were the reasons for that absence from work? Lack of wo"
label variable WH4_Q370_C04 "What were the reasons for that absence from work? Quit job."
label variable WH4_Q370_C05 "What were the reasons for that absence from work? Fired/disc"
label variable WH4_Q370_C06 "What were the reasons for that absence from work? Business o"
label variable WH4_Q370_C07 "What were the reasons for that absence from work? Moved or t"
label variable WH4_Q370_C08 "What were the reasons for that absence from work? Changed jo"
label variable WH4_Q370_C09 "What were the reasons for that absence from work? Own illnes"
label variable WH4_Q370_C10 "What were the reasons for that absence from work? Returned t"
label variable WH4_Q370_C11 "What were the reasons for that absence from work? Retired."
label variable WH4_Q370_C12 "What were the reasons for that absence from work? Maternity/"
label variable WH4_Q370_C13 "What were the reasons for that absence from work? Child care"
label variable WH4_Q370_C14 "What were the reasons for that absence from work? Eldercare."
label variable WH4_Q370_C15 "What were the reasons for that absence from work? Personal o"
label variable WH4_Q370_C16 "What were the reasons for that absence from work? Other."
label variable WH4_Q370_C17 "What were the reasons for that absence from work? To travel"
label variable WH4_Q410 "Did you return to seasonal work after that absence from work"
label variable WH4_Q420 "From [WH4_Q110M & WH4_Q110Y or WH4_Q260M & WH4_Q260Y or WH"
label variable WH5_Q100 "Did you start working after that absence from work?"
label variable AGE_WK5BEGC "Age of respondent at the beginning of fifth work period."
label variable AGE_WK5ENDC "Age of respondent at the end of fifth work period."
label variable DUR_WK5C "Length of respondent's fifth work period (in months)."
label variable WH5_Q115 "Did you return to the same job?"
label variable WH5_Q120 "Were you working 30 hours or more per week?"
label variable WH5_Q210C "Were you mainly:"
label variable WH5_Q230 "From [WH5_Q110M & WH5_Q110Y or WH5_Q200M & WH5_Q200Y] to tod"
label variable WH5_Q240 "From [WH5_Q110M & WH5_Q110Y or WH5_Q200M & WH5_Q200Y] to tod"
label variable WH5_Q255 "(You mentioned that you were absent from work for more than"
label variable WH5_Q310C "Were you mainly:"
label variable WH5_Q320 "Why did you work less than 30 hours per week?"
label variable WH5_Q330 "From [WH5_Q110M & WH5_Q110Y or WH5_Q200M & WH5_Q200Y or WH"
label variable WH5_Q340 "From [ WH5_Q110M & WH5_Q110Y or WH5_Q200M & WH5_Q200Y or W"
label variable WH5_Q355 "(You mentioned that you were absent from work for more than"
label variable WH5_Q370_C01 "What were the reasons for that absence from work? Seasonal/c"
label variable WH5_Q370_C02 "What were the reasons for that absence from work? Temporary"
label variable WH5_Q370_C03 "What were the reasons for that absence from work? Lack of wo"
label variable WH5_Q370_C04 "What were the reasons for that absence from work? Quit job."
label variable WH5_Q370_C05 "What were the reasons for that absence from work? Fired/disc"
label variable WH5_Q370_C06 "What were the reasons for that absence from work? Business o"
label variable WH5_Q370_C07 "What were the reasons for that absence from work? Moved or t"
label variable WH5_Q370_C08 "What were the reasons for that absence from work? Changed jo"
label variable WH5_Q370_C09 "What were the reasons for that absence from work? Own illnes"
label variable WH5_Q370_C10 "What were the reasons for that absence from work? Returned t"
label variable WH5_Q370_C11 "What were the reasons for that absence from work? Retired."
label variable WH5_Q370_C12 "What were the reasons for that absence from work? Maternity/"
label variable WH5_Q370_C13 "What were the reasons for that absence from work? Child care"
label variable WH5_Q370_C14C "What were the reasons for that absence from work? Eldercare."
label variable WH5_Q370_C15C "What were the reasons for that absence from work? Personal o"
label variable WH5_Q370_C16 "What were the reasons for that absence from work? Other."
label variable WH5_Q370_C17 "What were the reasons for that absence from work? To travel"
label variable WH5_Q410 "Did you return to seasonal work after that absence from work"
label variable NO_WKFULL "Number of full-time work periods."
label variable NO_WKPART_C "Number of part-time work periods."
label variable NO_WKPER "Total number of work periods."
label variable AGE_RETIRED_C "Age of respondent when he retired."
label variable WKSTATUS "Respondent's work status since beginning of career."
label variable WKTYPE "Work type since beginning of career."
label variable DUR_WKTOT "Length of respondent's total work period (in months), since"
label variable NO_INT "Total number of work interruptions the respondent has had."
label variable AGE_INT1BEGC "Respondent's age at the beginning of the first work interrup"
label variable AGE_INT1ENDC "Respondent's age at the end of the first work interruption."
label variable DUR_INT1C "Length of respondent's first work interruption (in months)."
label variable RANK_INT1 "Rank of respondent's first work absence among all work perio"
label variable AGE_INT2BEGC "Respondent's age at the beginning of the second work absence"
label variable AGE_INT2ENDC "Respondent's age at the end of the second work absence."
label variable DUR_INT2C "Length of respondent's second work absence (in months)."
label variable RANK_INT2 "Rank of respondent's second work absence among all work peri"
label variable AGE_INT3BEGC "Respondent's age at the beginning of the third work absence."
label variable AGE_INT3ENDC "Respondent's age at the end of the third work absence."
label variable DUR_INT3C "Length of respondent's third work absence (in months)."
label variable RANK_INT3 "Rank of respondent's third work absence among all work perio"
label variable AGE_INT4BEGC "Respondent's age at the beginning of the fourth work absence"
label variable AGE_INT4ENDC "Respondent's age at the end of the fourth work absence."
label variable DUR_INT4C "Length of respondent's fourth work absence (in months)."
label variable RANK_INT4 "Rank of respondent's fourth work absence among all work peri"
label variable AGE_INT5BEGC "Respondent's age at the beginning of the fifth work absence."
label variable AGE_INT5END "Respondent's age at the end of the fifth work absence."
label variable DUR_INT5 "Length of respondent's fifth work absence (in months)."
label variable RANK_INT5 "Rank of respondent's fifth work absence among all work perio"
label variable NO_MAT_PATC "Number of maternity/paternity leaves taken by respondent."
label variable AGE_MAT_PAT1BEGC "Age of respondent at the beginning of her/his first maternit"
label variable AGE_MAT_PAT1ENDC "Age of respondent at the end of her/his first maternity/pate"
label variable DUR_MAT_PAT1C "Length of respondent's first maternity/paternity leave (in m"
label variable AGE_MAT_PAT2BEGC "Age of respondent at the beginning of her/his second materni"
label variable AGE_MAT_PAT2ENDC "Age of respondent at the end of her/his second maternity/pat"
label variable DUR_MAT_PAT2C "Length of respondent's second maternity/paternity leave (in"
label variable AGE_MAT_PAT3BEGC "Age of respondent at the beginning of her/his third maternit"
label variable AGE_MAT_PAT3ENDC "Age of respondent at the end of her/his third maternity/pate"
label variable DUR_MAT_PAT3C "Length of respondent's third maternity/paternity leave (in m"
label variable LSR_Q100 "Using a scale of 0 to 10, where 0 means 'Very dissatisfied'"
label variable SRH_Q110 "In general, would you say your health is :"
label variable SRH_Q115 "In general, would you say your mental health is:"
label variable DWELCC "Dwelling type of the respondent."
label variable DWELLOWN "Dwelling owned by a member of the household."
label variable DOR_Q130 "Is there a mortgage on this dwelling?"
label variable LIVE_DWELLING "Length of time respondent has lived in current dwelling."
label variable LIVE_NEIGH "Length of time respondent has lived in current neighbourhood"
label variable LIVE_LOCAL "Length of time respondent has lived in current city or local"
label variable BRTHCAN "Country of birth of the respondent."
label variable BRTHPRVC "Province of birth of respondent."
label variable BRTHREGC "Country or region of birth of the respondent."
label variable YRARRIC "Range of years when the respondent first came to Canada."
label variable AGEARRIGRC "Age groups of the respondent when first came to Canada."
label variable BPR_Q50 "Are you now, or have you ever been, a landed immigrant in Ca"
label variable YRLNDIMM "Year respondent got his landed immigrant status."
label variable AGELNDIMMGRC "Age groups of the respondent when received landed immigrant"
label variable BRTHPCAN "Country of birth of respondent's spouse/partner."
label variable BRTHPPRVC "Province of birth of respondent's spouse/partner."
label variable BRTHPREGC "Country or region of birth of the respondent's spouse/partne"
label variable VISMINC "Visible minority status of the respondent."
label variable VISMINPRC "Visible minority status of the respondent's spouse/partner."
label variable RELIGATT "Religious attendance of the respondent."
label variable RLR_Q110 "How important are your religious or spiritual beliefs to the"
label variable RLR_Q120 "In the past 12 months, how often did you practice religious"
label variable RELIG6C "Religion of respondent - 6 categories."
label variable LANCH "First childhood language of the respondent."
label variable LANCHSUEC "Respondent still understands first childhood language - Engl"
label variable LANCHSUF "Respondent still understands first childhood language - Fren"
label variable LANCHSUO "Respondent still understands first childhood language - Othe"
label variable LANHSDC "Respondent's household language."
label variable INR_Q025 "What was your main source of income during the year ending D"
label variable INCMC "Annual personal income of the respondent."
label variable INCMMEMC "Not including the respondent, number of household members re"
label variable INCMHSDC "Total household income."
label variable WTBS_001 "Bootstrap weight # 1 for personal weight."
forvalues i = 1/500 {
	local longi = strofreal(`i',"%03.0f")
	label variable WTBS_`longi' "Bootstrap weight # `i' for personal weight."
}
